Update build_workflow_mir3g_MediaTek7621A_MIPS.yml

diff --git a/.github/workflows/build_workflow_mir3g_MediaTek7621A_MIPS.yml b/.github/workflows/build_workflow_mir3g_MediaTek7621A_MIPS.yml
--- a/.github/workflows/build_workflow_mir3g_MediaTek7621A_MIPS.yml
+++ b/.github/workflows/build_workflow_mir3g_MediaTek7621A_MIPS.yml
@@ -74,7 +74,10 @@ jobs:
     - name: Load custom configuration
       run: |
         [ -e files ] && mv files openwrt/files
-        [ ! -f $CONFIG_FILE ] && { echo "$CONFIG_FILE not found!"; exit 1 }
+        if [ ! -f $CONFIG_FILE ]; then
+          echo "$CONFIG_FILE not found!"
+          exit 1
+        fi
         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
         chmod +x $DIY_P2_SH
         cd openwrt
